#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libspectre
Version  : 0.2.8
Release  : 3
URL      : https://libspectre.freedesktop.org/releases/libspectre-0.2.8.tar.gz
Source0  : https://libspectre.freedesktop.org/releases/libspectre-0.2.8.tar.gz
Summary  : libgs wrapper library
Group    : Development/Tools
License  : GPL-2.0
Requires: libspectre-lib
BuildRequires : ghostscript-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-png)

%description
What is libspectre
==================
libspectre is a small library for rendering Postscript documents. It
provides a convenient easy to use API for handling and rendering
Postscript documents.

%package dev
Summary: dev components for the libspectre package.
Group: Development
Requires: libspectre-lib
Provides: libspectre-devel

%description dev
dev components for the libspectre package.


%package lib
Summary: lib components for the libspectre package.
Group: Libraries

%description lib
lib components for the libspectre package.


%prep
%setup -q -n libspectre-0.2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1511907662
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1511907662
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libspectre/spectre-document.h
/usr/include/libspectre/spectre-exporter.h
/usr/include/libspectre/spectre-macros.h
/usr/include/libspectre/spectre-page.h
/usr/include/libspectre/spectre-render-context.h
/usr/include/libspectre/spectre-status.h
/usr/include/libspectre/spectre-version.h
/usr/include/libspectre/spectre.h
/usr/lib64/libspectre.so
/usr/lib64/pkgconfig/libspectre.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspectre.so.1
/usr/lib64/libspectre.so.1.1.8
